### ISSUE TITLE
Thread-safety and HashMap

### ISSUE THREAD

**Issue by NicolasT** [sellerlabs/monad-metrics#5]
Given the use of an `IORef` to store the `Map` of metrics created in the `Store`, is this safe when multiple threads register a 'fresh' metric concurrently?

I guess using an `MVar` instead of an `IORef` could make this safe (or, alternatively, use STM).

Also (unrelated): did you benchmark using `Data.HashMap.*` from `unordered-containers` instead of `Data.Map`? Given the key always to be `Text`, which is `Hashable`, this could yield some performance benefits.

**Comment by parsonsmatt** [comment]
Good catch. There is a race condition in the code as-exists. If two threads try to register a metric at the same time that is not currently registered, then one might get thrown away.

I believe this could be fixed with using `atomicModifyIORef'` without having to resort to higher-overhead `MVar`. We'd need to use `unsafeInterleaveIO` to lazily create the metric outside of the modification callback.

I did not benchmark `Map` vs `HashMap`. I have not usually found there to be a huge difference in performance unless the maps are absolutely huge, and for smaller maps, the hashing overhead can be pretty big.

**Comment by NicolasT** [comment]
The first registration of said metric could be thrown away, but then on some subsequent invocation of the same metric, EKG could throw because the name was registered before, IIRC.

I agree with the `IORef` vs. `MVar` perf difference. I'm not familiar with `atomicModifyIORef'` (yet), will take a look and try to get things to work. If that doesn't work out, an `MVar` could be used to coordinate 'mutation' of the `Map`, which would only be required whenever the metric is registered, i.e. not impact any later registrations perf-wise.

I'll benchmark `Map Text Counter` and others vs. the `HashMap` equivalents as well.

**Comment by parsonsmatt** [comment]
Thanks! I've made #6 to address this issue. 

`atomicModifyIORef'` does what it says on the tin -- the IORef is locked while the function is running, so you're guaranteed that the read/write operate on the same value without interruption. I had to use `unsafeInterleaveIO` to get the creation of the counter to be sufficiently lazy.

**Comment by NicolasT** [comment]
`Map` vs. `HashMap`: https://github.com/NicolasT/monad-metrics/commit/f5e2e3c667f5bd2c5d32f8ff3b3a434b6a6bc6a5

Seems worth it (at least for the set of metric names used in the benchmark).

**Comment by parsonsmatt** [comment]
Nice, thanks for the benchmark! Would you be willing to open a PR to include that in the repo?

I'd be willing to shift internal representation to a HashMap.

**Comment by NicolasT** [comment]
Not sure it makes sense to have this one-of benchmark, which is barely related to the functionality of this package, contained in the package? I could open a PR though, maybe for historical purposes only.

**Comment by parsonsmatt** [comment]
This issue is resolved as of version 0.2.0.0 on Hackage :)
